apiVersion: v1
kind: Pod
metadata:
  name: initpod
spec:
  containers:
  - name: container1
    image: nginx
  initContainers:
  - name: initcontainer
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 60']
