apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: localdisk
provisioner: kubernetes.io/no-provisioner
allowVolumeExpansion: true
# creation of SC is automatic when creating PV if not already created
# but doesn't have allowVolumeExpansion: true
